const { get, run } = require('../../server/turso-db');

/**
 * Seed Word Search Words
 */
async function seedWords() {
    console.log('🔤 Seeding word search words...');

    // Mots génériques (disponibles pour tous - theme_slug = NULL)
    // Format: [mot, définition]
    const genericWords = [
        // Nature
        ['SOLEIL', 'Étoile au centre du système solaire'],
        ['ARBRE', 'Plante avec un tronc et des branches'],
        ['FLEUR', 'Partie colorée d\'une plante'],
        ['NUAGE', 'Amas de vapeur d\'eau dans le ciel'],
        ['PLUIE', 'Eau qui tombe du ciel'],
        ['NEIGE', 'Cristaux de glace qui tombent'],
        ['VENT', 'Mouvement de l\'air'],
        ['ORAGE', 'Pluie avec tonnerre et éclairs'],
        ['MONTAGNE', 'Très grande élévation de terre'],
        ['RIVIERE', 'Cours d\'eau qui coule'],
        ['FORET', 'Grand espace plein d\'arbres'],
        ['PLAGE', 'Bord de mer avec du sable'],
        ['JARDIN', 'Terrain avec des plantes'],
        ['PRAIRIE', 'Grande étendue d\'herbe'],
        ['LAC', 'Grande étendue d\'eau douce'],
        ['MER', 'Grande étendue d\'eau salée'],

        // Animaux
        ['CHAT', 'Petit félin domestique'],
        ['CHIEN', 'Animal fidèle de l\'homme'],
        ['OISEAU', 'Animal avec des plumes qui vole'],
        ['POISSON', 'Animal qui vit dans l\'eau'],
        ['PAPILLON', 'Insecte aux ailes colorées'],
        ['ABEILLE', 'Insecte qui fait du miel'],
        ['FOURMI', 'Petit insecte très travailleur'],
        ['COCCINELLE', 'Petit insecte rouge à pois noirs'],
        ['SOURIS', 'Petit rongeur gris'],
        ['LAPIN', 'Animal aux longues oreilles'],
        ['OURS', 'Grand mammifère poilu'],
        ['LION', 'Grand félin, roi des animaux'],
        ['TIGRE', 'Grand félin rayé'],
        ['ELEPHANT', 'Gros animal avec une trompe'],
        ['GIRAFE', 'Animal au très long cou'],
        ['ZEBRE', 'Cheval rayé noir et blanc'],
        ['SINGE', 'Animal qui grimpe aux arbres'],
        ['SERPENT', 'Reptile sans pattes'],
        ['TORTUE', 'Reptile avec une carapace'],
        ['BALEINE', 'Plus gros animal marin'],
        ['REQUIN', 'Gros poisson avec des dents'],
        ['DAUPHIN', 'Mammifère marin intelligent'],
        ['CRABE', 'Crustacé avec des pinces'],
        ['CREVETTE', 'Petit crustacé marin'],
        ['GRENOUILLE', 'Petit amphibien qui saute'],
        ['CANARD', 'Oiseau aquatique qui fait coin'],
        ['POULE', 'Oiseau de basse-cour'],
        ['COQ', 'Mâle de la poule'],
        ['VACHE', 'Animal qui donne du lait'],
        ['MOUTON', 'Animal avec de la laine'],
        ['CHEVAL', 'Animal qu\'on peut monter'],
        ['ANE', 'Animal avec de longues oreilles'],

        // Nourriture
        ['POMME', 'Fruit rouge ou vert'],
        ['BANANE', 'Fruit jaune et courbé'],
        ['ORANGE', 'Fruit rond et orange'],
        ['FRAISE', 'Petit fruit rouge sucré'],
        ['CERISE', 'Petit fruit rouge à noyau'],
        ['RAISIN', 'Petits fruits en grappe'],
        ['MELON', 'Gros fruit d\'été sucré'],
        ['POIRE', 'Fruit jaune en forme de cloche'],
        ['CAROTTE', 'Légume orange et croquant'],
        ['TOMATE', 'Fruit rouge qu\'on mange'],
        ['SALADE', 'Feuilles vertes à manger'],
        ['PAIN', 'Aliment fait avec de la farine'],
        ['FROMAGE', 'Produit fait avec du lait'],
        ['LAIT', 'Boisson blanche des vaches'],
        ['CHOCOLAT', 'Friandise marron sucrée'],
        ['GATEAU', 'Pâtisserie sucrée'],
        ['BONBON', 'Petite friandise sucrée'],
        ['GLACE', 'Dessert glacé et sucré'],
        ['JUS', 'Boisson de fruits pressés'],
        ['BISCUIT', 'Petit gâteau sec'],
        ['CONFITURE', 'Fruits cuits avec du sucre'],
        ['MIEL', 'Substance sucrée des abeilles'],
        ['SOUPE', 'Plat liquide et chaud'],
        ['PIZZA', 'Plat italien avec de la pâte'],

        // Objets du quotidien
        ['MAISON', 'Bâtiment où on habite'],
        ['ECOLE', 'Lieu où on apprend'],
        ['LIVRE', 'Objet pour lire des histoires'],
        ['JOUET', 'Objet pour s\'amuser'],
        ['BALLON', 'Objet rond pour jouer'],
        ['VELO', 'Véhicule à deux roues'],
        ['POUPEE', 'Jouet en forme de bébé'],
        ['ROBOT', 'Machine qui peut bouger'],
        ['CRAYON', 'Outil pour dessiner'],
        ['STYLO', 'Outil pour écrire'],
        ['CAHIER', 'Livret pour écrire'],
        ['SAC', 'Objet pour transporter'],
        ['CHAISE', 'Meuble pour s\'asseoir'],
        ['TABLE', 'Meuble plat sur pieds'],
        ['LIT', 'Meuble pour dormir'],
        ['PORTE', 'Ouverture pour entrer'],
        ['FENETRE', 'Ouverture avec du verre'],
        ['LAMPE', 'Objet qui fait de la lumière'],
        ['HORLOGE', 'Objet qui donne l\'heure'],
        ['TELEPHONE', 'Appareil pour appeler'],
        ['ORDINATEUR', 'Machine électronique'],
        ['TELEVISION', 'Écran pour regarder'],
        ['RADIO', 'Appareil pour écouter'],

        // Transports
        ['VOITURE', 'Véhicule à quatre roues'],
        ['TRAIN', 'Transport sur des rails'],
        ['AVION', 'Appareil qui vole'],
        ['BATEAU', 'Véhicule qui flotte'],
        ['BUS', 'Grand transport collectif'],
        ['CAMION', 'Gros véhicule pour transporter'],
        ['MOTO', 'Véhicule à deux roues motorisé'],
        ['TRACTEUR', 'Véhicule agricole'],
        ['HELICOPTERE', 'Appareil volant à hélices'],
        ['FUSEE', 'Engin qui va dans l\'espace'],
        ['METRO', 'Train sous terre'],
        ['TRAMWAY', 'Train de ville sur rails'],
        ['SKATE', 'Planche à roulettes'],
        ['TROTTINETTE', 'Planche avec guidon'],

        // Couleurs
        ['ROUGE', 'Couleur du sang'],
        ['BLEU', 'Couleur du ciel'],
        ['VERT', 'Couleur de l\'herbe'],
        ['JAUNE', 'Couleur du soleil'],
        ['NOIR', 'Couleur de la nuit'],
        ['BLANC', 'Couleur de la neige'],
        ['ROSE', 'Couleur claire et douce'],
        ['VIOLET', 'Mélange de rouge et bleu'],
        ['ORANGE', 'Mélange de rouge et jaune'],
        ['MARRON', 'Couleur du chocolat'],
        ['GRIS', 'Mélange de noir et blanc'],
        ['BEIGE', 'Couleur sable clair'],

        // Adjectifs
        ['GRAND', 'De grande taille'],
        ['PETIT', 'De petite taille'],
        ['CHAUD', 'À haute température'],
        ['FROID', 'À basse température'],
        ['HAUT', 'En hauteur'],
        ['BAS', 'Vers le sol'],
        ['RAPIDE', 'Qui va vite'],
        ['LENT', 'Qui va doucement'],
        ['HEUREUX', 'Qui ressent de la joie'],
        ['TRISTE', 'Qui a du chagrin'],
        ['JOYEUX', 'Plein de joie'],
        ['CONTENT', 'Satisfait et heureux'],
        ['DROLE', 'Qui fait rire'],
        ['GENTIL', 'Bon et agréable'],
        ['SAGE', 'Qui se comporte bien'],
        ['CALME', 'Tranquille et paisible'],
        ['FORT', 'Qui a de la puissance'],
        ['FAIBLE', 'Qui manque de force'],
        ['LEGER', 'Qui pèse peu'],
        ['LOURD', 'Qui pèse beaucoup'],
        ['DUR', 'Qui résiste au toucher'],
        ['MOU', 'Qui se déforme facilement'],
        ['DOUX', 'Agréable au toucher'],
        ['RUGUEUX', 'Qui racle la peau'],

        // Corps et sentiments
        ['TETE', 'Partie haute du corps'],
        ['MAIN', 'Partie au bout du bras'],
        ['PIED', 'Partie au bout de la jambe'],
        ['BRAS', 'Membre supérieur du corps'],
        ['JAMBE', 'Membre inférieur du corps'],
        ['OEIL', 'Organe pour voir'],
        ['NEZ', 'Organe pour sentir'],
        ['BOUCHE', 'Organe pour manger et parler'],
        ['OREILLE', 'Organe pour entendre'],
        ['COEUR', 'Organe qui bat dans la poitrine'],
        ['AMOUR', 'Sentiment d\'affection'],
        ['AMITIE', 'Relation entre amis'],
        ['PEUR', 'Sentiment de danger'],
        ['COURAGE', 'Force face au danger'],
        ['FORCE', 'Pouvoir physique'],
        ['JOIE', 'Sentiment de bonheur'],

        // Eléments
        ['EAU', 'Liquide transparent'],
        ['FEU', 'Flammes qui brûlent'],
        ['TERRE', 'Sol sous nos pieds'],
        ['AIR', 'Gaz qu\'on respire'],
        ['PIERRE', 'Roche dure et solide'],
        ['SABLE', 'Petits grains sur la plage'],
        ['BOIS', 'Matière des arbres'],
        ['METAL', 'Matière dure et brillante'],

        // Famille et personnes
        ['FAMILLE', 'Groupe de parents proches'],
        ['AMI', 'Personne qu\'on aime bien'],
        ['PAPA', 'Père d\'un enfant'],
        ['MAMAN', 'Mère d\'un enfant'],
        ['FRERE', 'Fils des mêmes parents'],
        ['SOEUR', 'Fille des mêmes parents'],
        ['BEBE', 'Très jeune enfant'],
        ['ENFANT', 'Jeune garçon ou fille'],
        ['MAITRE', 'Personne qui enseigne'],
        ['DOCTEUR', 'Personne qui soigne'],
        ['POMPIER', 'Personne qui éteint les feux'],
        ['POLICIER', 'Personne qui protège'],
        ['CUISINIER', 'Personne qui fait à manger'],
        ['ARTISTE', 'Personne qui crée des œuvres'],

        // Activités
        ['JOUER', 'S\'amuser avec des jeux'],
        ['COURIR', 'Aller vite avec ses jambes'],
        ['SAUTER', 'S\'élever en l\'air'],
        ['NAGER', 'Se déplacer dans l\'eau'],
        ['DANSER', 'Bouger son corps en rythme'],
        ['CHANTER', 'Faire de la musique avec sa voix'],
        ['LIRE', 'Comprendre un texte écrit'],
        ['ECRIRE', 'Tracer des mots'],
        ['DESSINER', 'Faire une image'],
        ['PEINDRE', 'Créer avec de la peinture'],
        ['CONSTRUIRE', 'Assembler pour créer'],
        ['DORMIR', 'Fermer les yeux et se reposer'],
        ['MANGER', 'Avaler de la nourriture'],
        ['BOIRE', 'Avaler un liquide'],

        // Moments
        ['JOUR', 'Période de lumière'],
        ['NUIT', 'Période d\'obscurité'],
        ['MATIN', 'Début de la journée'],
        ['SOIR', 'Fin de la journée'],
        ['PRINTEMPS', 'Saison des fleurs'],
        ['ETE', 'Saison chaude'],
        ['AUTOMNE', 'Saison des feuilles mortes'],
        ['HIVER', 'Saison froide'],
        ['LUNDI', 'Premier jour de la semaine'],
        ['MARDI', 'Deuxième jour de la semaine'],
        ['MERCREDI', 'Troisième jour de la semaine'],
        ['JEUDI', 'Quatrième jour de la semaine'],
        ['VENDREDI', 'Cinquième jour de la semaine'],
        ['SAMEDI', 'Sixième jour de la semaine'],
        ['DIMANCHE', 'Septième jour de la semaine']
    ];

    // Mots par thème de cartes
    // Format: [mot, définition]
    const wordLists = {
        minecraft: [
            // Monstres et créatures hostiles
            ['CREEPER', 'Monstre vert qui explose'],
            ['ZOMBIE', 'Mort-vivant hostile'],
            ['SQUELETTE', 'Monstre archer'],
            ['ARAIGNEE', 'Monstre à huit pattes'],
            ['ENDERMAN', 'Créature téléportante noire'],
            ['SLIME', 'Cube vert qui saute'],
            ['WITHER', 'Boss à trois têtes noires'],
            ['BLAZEHUM', 'Créature de feu du Nether'],
            ['GHAST', 'Méduse volante du Nether'],
            ['GARDIEN', 'Monstre aquatique épineux'],
            ['SORCIERE', 'Lance des potions'],
            ['PILLARD', 'Bandit hostile'],
            ['RAVAGEUR', 'Grande bête de raid'],
            ['EVOCATEUR', 'Invoque des créatures'],
            ['VINDICATEUR', 'Combattant à la hache'],
            ['PHANTOM', 'Volant de la nuit'],
            ['NOYEUR', 'Zombie aquatique'],
            ['HUSK', 'Zombie du désert'],
            ['STRAY', 'Squelette des neiges'],

            // Minerais et ressources
            ['DIAMANT', 'Minerai bleu très rare'],
            ['EMERAUDE', 'Minerai vert pour échanger'],
            ['FER', 'Minerai gris commun'],
            ['CHARBON', 'Combustible noir'],
            ['REDSTONE', 'Minerai rouge électrique'],
            ['LAPIS', 'Pierre bleue pour enchanter'],
            ['QUARTZ', 'Minerai blanc du Nether'],
            ['NETHERITE', 'Matériau le plus résistant'],
            ['CUIVRE', 'Minerai orange conducteur'],
            ['AMETHYSTE', 'Cristal violet brillant'],
            ['OR', 'Minerai jaune précieux'],

            // Outils et objets
            ['PIOCHE', 'Outil pour miner des blocs'],
            ['EPEE', 'Arme de combat'],
            ['HACHE', 'Outil pour couper'],
            ['PELLE', 'Outil pour creuser'],
            ['HOUE', 'Outil pour labourer'],
            ['ARC', 'Arme de tir à distance'],
            ['ARBALETE', 'Arme à carreaux'],
            ['FLECHE', 'Projectile de l\'arc'],
            ['BOUCLIER', 'Protection contre attaques'],
            ['ARMURE', 'Protection du corps'],
            ['COFFRE', 'Bloc pour stocker des objets'],
            ['FOURNEAU', 'Cuire et fondre'],
            ['ENCLUME', 'Réparer et renommer'],
            ['TABLE', 'Créer des objets'],
            ['TONNEAU', 'Stockage alternatif'],
            ['LUTRIN', 'Support pour livre'],
            ['COMPOSTEUR', 'Fabrique de l\'engrais'],
            ['CANNE', 'Pour pêcher'],
            ['BRIQUET', 'Allumer le feu'],
            ['SEAU', 'Transporter des liquides'],
            ['CISAILLES', 'Couper la laine'],
            ['BOUSSOLE', 'Indiquer la direction'],
            ['HORLOGE', 'Indiquer l\'heure'],
            ['CARTE', 'Explorer le monde'],
            ['LIVRE', 'Stocker des connaissances'],
            ['PAPIER', 'Pour écrire'],
            ['ENCRE', 'Pour signer'],

            // Blocs et matériaux
            ['BLOC', 'Élément de base du monde'],
            ['PIERRE', 'Bloc rocheux gris'],
            ['BOIS', 'Matériau des arbres'],
            ['PLANCHES', 'Bois transformé'],
            ['SABLE', 'Bloc qui tombe'],
            ['GRAVIER', 'Bloc gris qui tombe'],
            ['TERRE', 'Sol naturel'],
            ['HERBE', 'Terre avec végétation'],
            ['NEIGE', 'Bloc blanc froid'],
            ['GLACE', 'Eau gelée glissante'],
            ['OBSIDIENNE', 'Roche noire très dure'],
            ['BEDROCK', 'Roche indestructible'],
            ['LAVE', 'Liquide orange brûlant'],
            ['EAU', 'Liquide bleu vital'],
            ['VERRE', 'Transparent et fragile'],
            ['VITRE', 'Panneau de verre'],
            ['LAINE', 'Bloc coloré doux'],
            ['BETON', 'Bloc solide coloré'],
            ['BRIQUE', 'Bloc de construction rouge'],
            ['TNT', 'Explosif rouge et blanc'],
            ['ECHELLE', 'Pour grimper'],
            ['PORTAIL', 'Structure pour voyager'],
            ['RAIL', 'Pour les wagonnets'],
            ['DALLE', 'Demi-bloc'],
            ['ESCALIER', 'Marches'],
            ['BARRIERE', 'Clôture'],
            ['PORTILLON', 'Porte de clôture'],
            ['TRAPPE', 'Ouverture au sol'],
            ['PORTE', 'Entrée'],

            // Plantes et culture
            ['BLE', 'Culture dorée'],
            ['CAROTTE', 'Légume orange'],
            ['POMME', 'Fruit des arbres'],
            ['PATATE', 'Tubercule'],
            ['BETTERAVE', 'Racine rouge'],
            ['CANNE', 'Pour le sucre'],
            ['CACTUS', 'Plante qui pique'],
            ['CHAMPIGNON', 'Plante du sous-bois'],
            ['BAIES', 'Fruits des buissons'],
            ['BAMBOU', 'Plante haute'],
            ['ALGUE', 'Plante aquatique'],
            ['FLEUR', 'Plante décorative'],
            ['TULIPE', 'Fleur colorée'],
            ['ROSE', 'Fleur rouge'],
            ['PISSENLIT', 'Fleur jaune'],
            ['ORCHIDEE', 'Fleur rare'],
            ['VIGNE', 'Plante grimpante'],
            ['ARBRE', 'Grande plante'],
            ['CHENE', 'Arbre robuste'],
            ['BOULEAU', 'Arbre blanc'],
            ['SAPIN', 'Arbre des neiges'],
            ['ACACIA', 'Arbre du désert'],
            ['JUNGLE', 'Arbre tropical'],

            // Animaux
            ['POULET', 'Oiseau de ferme'],
            ['VACHE', 'Animal qui donne du lait'],
            ['MOUTON', 'Animal à laine'],
            ['COCHON', 'Animal rose'],
            ['CHEVAL', 'Animal à monter'],
            ['LOUP', 'Animal apprivoisable'],
            ['CHAT', 'Félin domestique'],
            ['PERROQUET', 'Oiseau coloré'],
            ['PANDA', 'Ours noir et blanc'],
            ['RENARD', 'Animal rusé orange'],
            ['OURS', 'Grand animal polaire'],
            ['ABEILLE', 'Insecte qui fait du miel'],
            ['TORTUE', 'Reptile marin'],
            ['DAUPHIN', 'Mammifère intelligent'],
            ['PIEUVRE', 'Mollusque à tentacules'],
            ['SAUMON', 'Poisson rose'],
            ['MORUE', 'Poisson commun'],
            ['LAPIN', 'Petit animal sauteur'],
            ['OCELOT', 'Félin sauvage'],
            ['STRIDER', 'Marcheur sur lave'],
            ['HOGLIN', 'Sanglier du Nether'],
            ['AXOLOTL', 'Amphibien mignon'],
            ['GRENOUILLE', 'Amphibien sauteur'],
            ['ALLAY', 'Petite fée bleue'],

            // Villages et structures
            ['VILLAGEOIS', 'Habitant des villages'],
            ['VILLAGE', 'Groupe de maisons'],
            ['FERME', 'Lieu pour cultiver'],
            ['FORGE', 'Atelier du forgeron'],
            ['EGLISE', 'Bâtiment religieux'],
            ['PUITS', 'Source d\'eau'],
            ['MAISON', 'Habitation'],
            ['GOLEM', 'Créature qui protège'],
            ['TEMPLE', 'Structure ancienne'],
            ['DONJON', 'Prison souterraine'],
            ['FORTERESSE', 'Grande structure'],
            ['MANOIR', 'Grande demeure'],
            ['PYRAMIDE', 'Structure du désert'],
            ['IGLOO', 'Maison de glace'],
            ['EPAVE', 'Bateau coulé'],
            ['RUINE', 'Structure détruite'],

            // Dimensions
            ['NETHER', 'Dimension infernale'],
            ['END', 'Dimension finale'],
            ['DRAGON', 'Boss de l\'End'],
            ['BIOME', 'Type de terrain naturel'],
            ['DESERT', 'Biome de sable'],
            ['JUNGLE', 'Biome tropical'],
            ['TOUNDRA', 'Biome glacé'],
            ['SAVANE', 'Biome aride'],
            ['MARAIS', 'Biome humide'],
            ['OCEAN', 'Biome aquatique'],
            ['TAIGA', 'Forêt froide'],
            ['PLAINES', 'Terrain plat'],
            ['COLLINES', 'Relief ondulé'],
            ['MONTAGNE', 'Relief élevé'],

            // Jeu et mécaniques
            ['CRAFT', 'Fabrication d\'objets'],
            ['MINE', 'Creuser sous terre'],
            ['ENCHANTEMENT', 'Amélioration magique'],
            ['POTION', 'Boisson aux effets'],
            ['ALCHIMIE', 'Créer des potions'],
            ['EXPERIENCE', 'Points accumulés'],
            ['NIVEAU', 'Palier d\'expérience'],
            ['SORT', 'Pouvoir magique'],
            ['SURVIE', 'Mode de jeu'],
            ['CREATIF', 'Mode sans limite'],
            ['AVENTURE', 'Mode d\'exploration'],
            ['HARDCORE', 'Mode difficile'],
            ['MULTIJOUEUR', 'Jouer ensemble'],
            ['SERVEUR', 'Monde partagé'],
            ['SPAWN', 'Point d\'apparition'],
            ['LIT', 'Dormir et réapparaître']
        ],
        space: [
            // Planètes du système solaire
            ['MERCURE', 'Planète la plus proche du Soleil'],
            ['VENUS', 'Deuxième planète, très chaude'],
            ['TERRE', 'Notre planète bleue'],
            ['MARS', 'Planète rouge'],
            ['JUPITER', 'Plus grosse planète gazeuse'],
            ['SATURNE', 'Planète aux anneaux'],
            ['URANUS', 'Géante glacée penchée'],
            ['NEPTUNE', 'Huitième planète bleue'],
            ['PLUTON', 'Planète naine lointaine'],
            ['PLANETE', 'Corps céleste qui tourne'],

            // Astres et phénomènes
            ['SOLEIL', 'Étoile du système'],
            ['ETOILE', 'Astre brillant la nuit'],
            ['LUNE', 'Satellite naturel de la Terre'],
            ['COMETE', 'Astre avec une queue'],
            ['ASTEROIDE', 'Petit rocher spatial'],
            ['METEORITE', 'Roche tombée du ciel'],
            ['METEOROIDE', 'Petit corps rocheux'],
            ['BOLIDE', 'Météore très brillant'],
            ['NOVA', 'Explosion stellaire'],
            ['SUPERNOVA', 'Explosion d\'étoile géante'],
            ['PULSAR', 'Étoile à neutrons qui pulse'],
            ['QUASAR', 'Noyau galactique lumineux'],
            ['NEBULEUSE', 'Nuage de gaz spatial'],
            ['GALAXIE', 'Amas d\'étoiles géant'],
            ['VOIELACTEE', 'Notre galaxie spirale'],
            ['TROU', 'Région d\'espace-temps'],
            ['AMAS', 'Groupe d\'étoiles'],
            ['CONSTELLATION', 'Groupe d\'étoiles visible'],
            ['ECLIPSE', 'Occultation d\'un astre'],
            ['AURORE', 'Lumières polaires'],
            ['RAYONS', 'Particules solaires'],
            ['VENT', 'Flux de particules'],

            // Lunes célèbres
            ['PHOBOS', 'Lune de Mars'],
            ['DEIMOS', 'Petite lune martienne'],
            ['IO', 'Lune volcanique'],
            ['EUROPE', 'Lune glacée'],
            ['GANYMEDE', 'Plus grande lune'],
            ['CALLISTO', 'Lune cratérisée'],
            ['TITAN', 'Lune avec atmosphère'],
            ['ENCELADE', 'Lune avec geysers'],
            ['TRITON', 'Lune de Neptune'],
            ['CHARON', 'Lune de Pluton'],

            // Espace et cosmos
            ['ESPACE', 'Vide entre les astres'],
            ['COSMOS', 'Univers entier'],
            ['UNIVERS', 'Tout ce qui existe'],
            ['VIDE', 'Absence de matière'],
            ['MATIERE', 'Substance de l\'univers'],
            ['ENERGIE', 'Force cosmique'],
            ['TEMPS', 'Dimension temporelle'],
            ['DIMENSION', 'Étendue de l\'espace'],
            ['INFINI', 'Sans limite'],
            ['ORBITE', 'Trajectoire circulaire'],
            ['GRAVITE', 'Force d\'attraction'],
            ['APESANTEUR', 'Absence de poids'],
            ['MAGNETIQUE', 'Force d\'attraction'],
            ['RADIATION', 'Émission d\'énergie'],
            ['LUMIERE', 'Onde électromagnétique'],
            ['SPECTRE', 'Décomposition de la lumière'],
            ['PHOTON', 'Particule de lumière'],

            // Missions et exploration
            ['APOLLO', 'Programme lunaire américain'],
            ['ARTEMIS', 'Nouveau programme lunaire'],
            ['VOYAGER', 'Sondes lointaines'],
            ['PIONEER', 'Premières sondes'],
            ['CASSINI', 'Mission vers Saturne'],
            ['JUNO', 'Sonde autour de Jupiter'],
            ['PERSEVERANCE', 'Rover sur Mars'],
            ['CURIOSITY', 'Robot martien'],
            ['INSIGHT', 'Atterrisseur martien'],
            ['OPPORTUNITY', 'Ancien rover martien'],
            ['SPIRIT', 'Jumeau d\'Opportunity'],
            ['ROVER', 'Robot explorateur mobile'],
            ['SONDE', 'Vaisseau automatique'],
            ['ORBITER', 'Satellite en orbite'],
            ['ATTERRISSEUR', 'Vaisseau qui se pose'],
            ['MODULE', 'Partie d\'un vaisseau'],
            ['CAPSULE', 'Habitacle spatial'],

            // Vaisseaux et équipement
            ['FUSEE', 'Véhicule spatial'],
            ['NAVETTE', 'Vaisseau réutilisable'],
            ['LANCEUR', 'Propulseur de fusée'],
            ['ETAGE', 'Section de fusée'],
            ['PROPULSEUR', 'Moteur spatial'],
            ['CARBURANT', 'Combustible de fusée'],
            ['ERGOL', 'Propergol de fusée'],
            ['BOOSTERS', 'Propulseurs d\'appoint'],
            ['PARACHUTE', 'Freiner la descente'],
            ['BOUCLIER', 'Protection thermique'],
            ['PANNEAU', 'Capteur solaire'],
            ['ANTENNE', 'Communication'],
            ['SATELLITE', 'Objet en orbite'],
            ['STATION', 'Base spatiale'],
            ['ISS', 'Station Spatiale Internationale'],
            ['MIR', 'Ancienne station russe'],
            ['SKYLAB', 'Première station américaine'],

            // Astronautes et agences
            ['ASTRONAUTE', 'Voyageur de l\'espace'],
            ['COSMONAUTE', 'Astronaute russe'],
            ['SPATIONAUTE', 'Astronaute français'],
            ['PILOTE', 'Commandant de vaisseau'],
            ['INGENIEUR', 'Technicien spatial'],
            ['SCIENTIFIQUE', 'Chercheur spatial'],
            ['EQUIPAGE', 'Équipe d\'astronautes'],
            ['NASA', 'Agence américaine'],
            ['ESA', 'Agence européenne'],
            ['ROSCOSMOS', 'Agence russe'],
            ['CNSA', 'Agence chinoise'],
            ['JAXA', 'Agence japonaise'],
            ['SPACEX', 'Entreprise privée'],
            ['CNES', 'Agence française'],

            // Équipement d\'astronaute
            ['SCAPHANDRE', 'Combinaison spatiale'],
            ['CASQUE', 'Protection de la tête'],
            ['GANTS', 'Protection des mains'],
            ['BOTTES', 'Chaussures spatiales'],
            ['OXYGENE', 'Air respirable'],
            ['VISIERE', 'Protection des yeux'],
            ['JETPACK', 'Propulseur dorsal'],
            ['ATTACHE', 'Lien de sécurité'],
            ['SONDE', 'Instrument de mesure'],

            // Observation
            ['TELESCOPE', 'Lunette pour voir loin'],
            ['HUBBLE', 'Télescope spatial célèbre'],
            ['JAMES', 'Nouveau télescope spatial'],
            ['OBSERVATOIRE', 'Centre d\'observation'],
            ['PLANETARIUM', 'Simulateur de ciel'],
            ['JUMELLES', 'Observer les étoiles'],
            ['SPECTROSCOPE', 'Analyser la lumière'],
            ['RADAR', 'Détection par ondes'],
            ['CAMERA', 'Capturer des images'],
            ['CAPTEUR', 'Mesurer les données'],

            // Cratères lunaires célèbres
            ['CRATERE', 'Trou d\'impact'],
            ['COPERNIC', 'Cratère lunaire brillant'],
            ['TYCHO', 'Grand cratère avec rayons'],
            ['KEPLER', 'Cratère bien visible'],
            ['ARISTARQUE', 'Cratère le plus brillant'],
            ['PLATON', 'Cratère sombre'],

            // Concepts
            ['ANNEAU', 'Cercle autour d\'une planète'],
            ['PHASE', 'Aspect de la Lune'],
            ['MARE', 'Plaine lunaire sombre'],
            ['REGOLITE', 'Poussière lunaire'],
            ['BASALTE', 'Roche volcanique lunaire'],
            ['IMPESANTEUR', 'Flotter dans l\'espace'],
            ['DECOLLAGE', 'Lancement de fusée'],
            ['ATTERRISSAGE', 'Se poser'],
            ['AMARRAGE', 'Connexion de vaisseaux'],
            ['SORTIE', 'Marcher dans l\'espace'],
            ['MANOEUVRE', 'Changement de trajectoire'],
            ['RENDEZVOUS', 'Rendez-vous orbital'],
            ['REENTREE', 'Retour dans l\'atmosphère'],
            ['ECLABOUSSURE', 'Amerrissage'],
            ['LANCEMEN', 'Départ de fusée'],
            ['COMPTE', 'Décompte avant lancement'],
            ['MISSION', 'Expédition spatiale'],
            ['EXPLORATION', 'Découvrir l\'espace'],
            ['COLONISATION', 'S\'installer ailleurs'],
            ['TERRAFORMATION', 'Rendre habitable']
        ],
        dinosaurs: [
            // Dinosaures carnivores célèbres
            ['TREX', 'Tyrannosaure Rex, roi carnivore'],
            ['TYRANNOSAURE', 'Lézard tyran géant'],
            ['VELOCIRAPTOR', 'Petit dinosaure rapide'],
            ['RAPTOR', 'Dinosaure chasseur rapide'],
            ['ALLOSAURUS', 'Grand carnivore jurassique'],
            ['SPINOSAURE', 'Dinosaure à voile dorsale'],
            ['CARNOTAURE', 'Carnivore à cornes'],
            ['CERATOSAURE', 'Prédateur à corne nasale'],
            ['GIGANOTOSAURE', 'Géant carnivore argentin'],
            ['CARCHARODONTO', 'Dent de requin géant'],
            ['ACROCANTHO', 'Épine haute'],
            ['MEGALOSAURE', 'Grand lézard'],
            ['TORVOSAURE', 'Lézard sauvage'],
            ['DILOPHOSAURE', 'Double crête'],
            ['DEINONYCHUS', 'Griffe terrible'],
            ['UTAHRAPTOR', 'Grand raptor du Utah'],
            ['DROMAEOSAURE', 'Lézard coureur'],
            ['BARYONYX', 'Griffe lourde'],
            ['SUCHOMIMUS', 'Imitateur de crocodile'],
            ['MEGARAPTOR', 'Grand voleur'],
            ['COMPSOGNATHUS', 'Mâchoire délicate'],
            ['COELOPHYSIS', 'Forme creuse'],

            // Dinosaures herbivores géants
            ['TRICERATOPS', 'Dinosaure à trois cornes'],
            ['DIPLODOCUS', 'Dinosaure à long cou'],
            ['BRACHIOSAURE', 'Grand herbivore géant'],
            ['STEGOSAURE', 'Dinosaure à plaques dorsales'],
            ['ANKYLOSAURE', 'Dinosaure blindé'],
            ['IGUANODON', 'Herbivore à pouce pointu'],
            ['BRONTOSAURE', 'Lézard tonnerre'],
            ['APATOSAURE', 'Lézard trompeur'],
            ['CAMARASAURE', 'Lézard à chambres'],
            ['ARGENTINO', 'Géant d\'Argentine'],
            ['SAUROPOSEIDON', 'Dieu lézard séisme'],
            ['BRACHIOTRACHE', 'Cou de bras'],
            ['MAMENCHISAURE', 'Cou très très long'],
            ['SEISMOSAURE', 'Lézard séisme'],
            ['SUPERSAURE', 'Super lézard'],
            ['ALAMOSAURE', 'Lézard d\'Alamo'],

            // Dinosaures à cornes et plaques
            ['STYRACOSAURE', 'Lézard à piques'],
            ['PENTACERATOPS', 'Cinq cornes'],
            ['PROTOCERATOPS', 'Première tête cornue'],
            ['PACHYRHINO', 'Nez épais'],
            ['CENTROSAURUS', 'Lézard à pointe'],
            ['CHASMOSAURE', 'Lézard à ouverture'],
            ['TOROSAURUS', 'Lézard taureau'],
            ['KOSMOCERATOPS', 'Corne cosmique'],
            ['DIABLOCERATOPS', 'Corne du diable'],
            ['KENTROSAURUS', 'Lézard à piques'],
            ['TUOJIANGOSAURE', 'Lézard du fleuve'],
            ['HUAYANGOSAURE', 'Lézard de Huayang'],
            ['WUERHOSAURE', 'Lézard de Wuerho'],

            // Dinosaures à armure
            ['EUOPLOCEPHALE', 'Bien blindé'],
            ['NODOSAURE', 'Lézard noueux'],
            ['EDMONTONIA', 'D\'Edmonton'],
            ['SAUROPELTA', 'Bouclier lézard'],
            ['GASTONIA', 'Lézard de Gaston'],
            ['POLACANTHUS', 'Beaucoup d\'épines'],
            ['HYLAEOSAURE', 'Lézard des forêts'],
            ['MINMI', 'Petit blindé'],

            // Dinosaures à bec de canard
            ['PARASAUROLOPHUS', 'Crête tubulaire'],
            ['CORYTHOSAURE', 'Lézard à casque'],
            ['LAMBEOSAURE', 'Lézard de Lambe'],
            ['MAIASAURA', 'Bonne mère lézard'],
            ['EDMONTOSAURE', 'Lézard d\'Edmonton'],
            ['HADROSAURUS', 'Gros lézard'],
            ['SAUROLOPHUS', 'Crête lézard'],
            ['KRITOSAURE', 'Lézard séparé'],
            ['GRYPOSAURUS', 'Lézard à nez crochu'],
            ['TSINTAOSAURE', 'Lézard de Qingdao'],

            // Dinosaures à tête dure
            ['PACHYCEPHALO', 'Tête épaisse'],
            ['STEGOCERAS', 'Corne en toit'],
            ['DRACOREX', 'Roi dragon'],
            ['STYGIMOLOCH', 'Démon du Styx'],
            ['HOMALOCEPHALE', 'Tête plate'],

            // Dinosaures plumés
            ['ARCHEOPTERYX', 'Aile ancienne'],
            ['MICRORAPTOR', 'Petit voleur'],
            ['SINORNITHOSAURE', 'Lézard oiseau chinois'],
            ['CAUDIPTERYX', 'Queue à plumes'],
            ['BEIPIAOSAURE', 'Lézard de Beipiao'],
            ['YUTYRANNUS', 'Tyran plumeux'],
            ['DILONG', 'Dragon empereur'],
            ['SCIURUMIMUS', 'Imitateur d\'écureuil'],
            ['ANCHIORNIS', 'Presque oiseau'],
            ['AURORNIS', 'Oiseau de l\'aube'],

            // Reptiles marins
            ['MOSASAURE', 'Lézard de la Meuse'],
            ['PLESIOSAURE', 'Presque lézard'],
            ['ICHTHYOSAURE', 'Lézard poisson'],
            ['ELASMOSAURE', 'Lézard à plaques'],
            ['KRONOSAURUS', 'Lézard de Cronos'],
            ['LIOPLEURODON', 'Dent lisse'],
            ['TYLOSAURE', 'Lézard à bosse'],
            ['DAKOSAURUS', 'Lézard déchireur'],

            // Reptiles volants
            ['PTERODACTYLE', 'Doigt ailé'],
            ['PTERANODON', 'Ailé sans dents'],
            ['QUETZALCOATLUS', 'Serpent à plumes géant'],
            ['DIMORPHODON', 'Deux formes de dents'],
            ['RHAMPHORHYNQUE', 'Museau à bec'],
            ['TAPEJARA', 'Vieil être'],
            ['PTEROSAURE', 'Lézard ailé'],
            ['ANHANGUERA', 'Vieil esprit'],

            // Anatomie et paléontologie
            ['FOSSILE', 'Reste pétrifié ancien'],
            ['CRANE', 'Os de la tête'],
            ['SQUELETTE', 'Ensemble des os'],
            ['OS', 'Partie dure du corps'],
            ['DENT', 'Pour mâcher et mordre'],
            ['GRIFFE', 'Ongle pointu acéré'],
            ['ECAILLE', 'Plaque de peau'],
            ['PLUMES', 'Certains en avaient'],
            ['OEUFS', 'Naissance des dinosaures'],
            ['NID', 'Lieu de ponte'],
            ['EMPREINTE', 'Trace de pas fossilisée'],
            ['VERTEBRE', 'Os de la colonne'],
            ['FEMUR', 'Os de la cuisse'],
            ['MACHOIRE', 'Os avec les dents'],
            ['COLONNE', 'Suite de vertèbres'],
            ['QUEUE', 'Prolongement du corps'],
            ['COU', 'Partie entre tête et corps'],
            ['PATTE', 'Membre pour marcher'],
            ['GRIFFE', 'Ongle pointu'],
            ['ERGOT', 'Griffe du pouce'],
            ['CORNE', 'Excroissance pointue'],
            ['CRÊTE', 'Protubérance sur la tête'],
            ['PLAQUE', 'Os plat sur le dos'],
            ['PIQUE', 'Défense pointue'],
            ['ARMURE', 'Protection osseuse'],
            ['BOUCLIER', 'Protection corporelle'],
            ['MASSUE', 'Queue en forme de masse'],
            ['BEC', 'Bouche cornée'],
            ['NARINES', 'Orifices pour respirer'],
            ['ORBITE', 'Cavité de l\'œil'],
            ['COPROLITE', 'Excrément fossilisé'],
            ['GASTROLITE', 'Pierre d\'estomac'],

            // Périodes géologiques
            ['TRIAS', 'Première période'],
            ['JURASSIQUE', 'Période des dinosaures'],
            ['CRETACE', 'Dernière période'],
            ['MESOZOIQUE', 'Ère des dinosaures'],
            ['TRIASSIQUE', 'Période du Trias'],
            ['ERE', 'Grande division du temps'],
            ['PERIODE', 'Division géologique'],
            ['MILLIONS', 'Millions d\'années'],
            ['EXTINCTION', 'Disparition d\'espèces'],

            // Modes de vie
            ['HERBIVORE', 'Qui mange des plantes'],
            ['CARNIVORE', 'Qui mange de la viande'],
            ['OMNIVORE', 'Qui mange de tout'],
            ['PREDATEUR', 'Chasseur d\'autres animaux'],
            ['PROIE', 'Animal chassé'],
            ['CHASSE', 'Recherche de proies'],
            ['MEUTE', 'Groupe de chasseurs'],
            ['TROUPEAU', 'Groupe d\'herbivores'],
            ['MIGRATION', 'Déplacement saisonnier'],
            ['TERRITOIRE', 'Zone de vie'],
            ['DEFENSE', 'Protection contre danger'],
            ['COMBAT', 'Affrontement'],
            ['PARADE', 'Démonstration de séduction'],
            ['ACCOUPLEMENT', 'Reproduction'],
            ['INCUBATION', 'Couver les œufs'],
            ['ECLOSION', 'Sortie de l\'œuf'],
            ['JUVENILE', 'Jeune dinosaure'],
            ['ADULTE', 'Dinosaure mature'],

            // Recherche et découverte
            ['PALEONTOLOGIE', 'Science des fossiles'],
            ['PALEONTOLOGUE', 'Scientifique des fossiles'],
            ['FOUILLES', 'Recherche de fossiles'],
            ['EXCAVATION', 'Creuser pour trouver'],
            ['SITE', 'Lieu de découverte'],
            ['GISEMENT', 'Zone riche en fossiles'],
            ['COUCHE', 'Strate géologique'],
            ['SEDIMENT', 'Dépôt de particules'],
            ['ROCHE', 'Pierre contenant fossiles'],
            ['PIERRE', 'Matière minérale'],
            ['GRÈS', 'Roche sédimentaire'],
            ['SCHISTE', 'Roche en feuillets'],
            ['CALCAIRE', 'Roche à carbonate'],
            ['ARGILE', 'Terre fine compacte'],
            ['MUSEE', 'Lieu d\'exposition'],
            ['RECONSTITUTION', 'Recréer l\'apparence'],
            ['MOULAGE', 'Copie de fossile'],
            ['DATATION', 'Déterminer l\'âge'],

            // Environnement
            ['PREHISTOIRE', 'Temps avant l\'écriture'],
            ['PANGEE', 'Supercontinent ancien'],
            ['CONTINENT', 'Grande terre émergée'],
            ['JUNGLE', 'Forêt tropicale dense'],
            ['PLAINE', 'Vaste étendue plate'],
            ['MARAIS', 'Zone humide'],
            ['DESERT', 'Zone aride'],
            ['MONTAGNE', 'Relief élevé'],
            ['VOLCAN', 'Montagne de feu'],
            ['LAVE', 'Roche en fusion'],
            ['ERUPTION', 'Explosion volcanique'],
            ['SEISME', 'Tremblement de terre'],
            ['METEORITE', 'Roche de l\'espace'],
            ['IMPACT', 'Choc violent'],
            ['CRATERE', 'Trou d\'impact'],
            ['CLIMAT', 'Conditions météo'],
            ['FORET', 'Zone d\'arbres'],
            ['FOUGERE', 'Plante ancienne'],
            ['CONIFERE', 'Arbre à cônes'],
            ['CYCADE', 'Plante préhistorique'],
            ['GINKGO', 'Arbre fossile vivant'],
            ['PRELE', 'Plante primitive']
        ],
        monuments: [
            // Monuments égyptiens
            ['PYRAMIDE', 'Monument égyptien triangulaire'],
            ['KHEOPS', 'Grande pyramide de Gizeh'],
            ['KHEPHREN', 'Deuxième pyramide'],
            ['MYKÉRINOS', 'Troisième pyramide'],
            ['SPHINX', 'Statue lion à tête humaine'],
            ['OBELISQUE', 'Pierre dressée pointue'],
            ['KARNAC', 'Temple géant égyptien'],
            ['LOUXOR', 'Temple égyptien majestueux'],
            ['ABOU', 'Temple rupestre'],
            ['SIMBEL', 'Fin d\'Abou Simbel'],
            ['RAMSES', 'Pharaon bâtisseur'],
            ['PHILAE', 'Temple sur île'],
            ['DENDERA', 'Temple d\'Hathor'],
            ['EDFU', 'Temple d\'Horus'],
            ['HATSHEPSOUT', 'Temple de la reine'],
            ['VALLEE', 'Nécropole royale'],
            ['ROIS', 'Tombes des pharaons'],
            ['SAQQARAH', 'Nécropole ancienne'],
            ['DJOSER', 'Pyramide à degrés'],

            // Monuments grecs
            ['PARTHENON', 'Temple grec d\'Athènes'],
            ['ACROPOLE', 'Citadelle grecque haute'],
            ['ERECHTHEION', 'Temple aux Caryatides'],
            ['PROPYLEES', 'Entrée monumentale'],
            ['OLYMPIE', 'Sanctuaire de Zeus'],
            ['DELPHES', 'Oracle d\'Apollon'],
            ['EPIDAURE', 'Théâtre à l\'acoustique'],
            ['CORINTHE', 'Temple d\'Apollon'],
            ['OLYMPIEION', 'Temple de Zeus à Athènes'],
            ['ATHENA', 'Déesse d\'Athènes'],
            ['CARYATIDE', 'Colonne sculptée'],
            ['AGORA', 'Place publique antique'],

            // Monuments romains
            ['COLISEE', 'Arène romaine antique'],
            ['PANTHEON', 'Temple romain parfait'],
            ['FORUM', 'Place romaine'],
            ['ARENE', 'Lieu de spectacles'],
            ['AMPHITHEATRE', 'Gradins en cercle'],
            ['CARACALLA', 'Thermes romains'],
            ['TRAJAN', 'Colonne et marché'],
            ['CIRCUS', 'Hippodrome romain'],
            ['MAXIMUS', 'Grand cirque'],
            ['AQUEDUC', 'Pont pour l\'eau'],
            ['GARD', 'Aqueduc français'],
            ['NIMES', 'Arènes romaines'],
            ['ARLES', 'Amphithéâtre provençal'],
            ['ORANGE', 'Théâtre romain'],
            ['POMPEI', 'Ville ensevelie'],
            ['HERCULANUM', 'Cité romaine figée'],
            ['OSTIA', 'Port de Rome'],
            ['HADRIEN', 'Villa de l\'empereur'],
            ['TIBRE', 'Pont romain'],

            // Cathédrales et églises
            ['CATHEDRALE', 'Grande église'],
            ['BASILIQUE', 'Église importante'],
            ['CHAPELLE', 'Petite église'],
            ['EGLISE', 'Lieu de culte chrétien'],
            ['DAME', 'Notre-Dame de Paris'],
            ['CHARTRES', 'Cathédrale gothique'],
            ['REIMS', 'Cathédrale des sacres'],
            ['AMIENS', 'Plus vaste cathédrale'],
            ['STRASBOURG', 'Cathédrale rose'],
            ['BOURGES', 'Cathédrale Saint-Étienne'],
            ['ROUEN', 'Cathédrale normande'],
            ['BEAUVAIS', 'Voûte la plus haute'],
            ['COLOGNE', 'Cathédrale allemande'],
            ['MILAN', 'Duomo italien'],
            ['FLORENCE', 'Duomo et campanile'],
            ['SIENNE', 'Cathédrale rayée'],
            ['SAINT', 'Basilique de Pierre'],
            ['PIERRE', 'Vatican'],
            ['SAGRADA', 'Basilique de Barcelone'],
            ['FAMILIA', 'Suite de Sagrada'],
            ['SEVILLE', 'Cathédrale la plus vaste'],
            ['BURGOS', 'Cathédrale espagnole'],
            ['SANTIAGO', 'Fin du chemin'],
            ['COMPOSTELLE', 'Pèlerinage célèbre'],
            ['WESTMINSTER', 'Abbaye de Londres'],
            ['YORK', 'Cathédrale anglaise'],
            ['CANTERBURY', 'Siège primat'],
            ['BASILIQUE', 'Sacré-Cœur de Paris'],
            ['MONTMARTRE', 'Colline de Paris'],
            ['INVALIDES', 'Dôme parisien doré'],
            ['MADELEINE', 'Église néoclassique'],
            ['SAINTE', 'Chapelle aux vitraux'],

            // Mosquées et temples islamiques
            ['MOSQUEE', 'Lieu de culte musulman'],
            ['ALHAMBRA', 'Palais mauresque espagnol'],
            ['CORDOUE', 'Mosquée-cathédrale'],
            ['MEZQUITA', 'Grande mosquée'],
            ['BLEUE', 'Mosquée d\'Istanbul'],
            ['SOPHIE', 'Sainte-Sophie'],
            ['HAGIA', 'Début de Hagia Sophia'],
            ['SULEYMANIYE', 'Mosquée ottomane'],
            ['TOPKAPI', 'Palais du sultan'],
            ['HASSAN', 'Mosquée du Maroc'],
            ['KOUTOUBIA', 'Minaret de Marrakech'],
            ['OMEYYADES', 'Mosquée de Damas'],
            ['KAIROUAN', 'Grande mosquée tunisienne'],
            ['MEDINE', 'Mosquée du Prophète'],
            ['MECQUE', 'Lieu sacré de l\'islam'],
            ['KAABA', 'Pierre noire sacrée'],
            ['DOME', 'Dôme du Rocher'],
            ['ROCHER', 'Mont du Temple'],
            ['AQSA', 'Mosquée d\'Al-Aqsa'],

            // Temples asiatiques
            ['PAGODE', 'Temple asiatique à étages'],
            ['ANGKOR', 'Temple du Cambodge'],
            ['WAT', 'Temple cambodgien'],
            ['BAYON', 'Temple aux visages'],
            ['PREAH', 'Temple sacré'],
            ['BAGAN', 'Plaine aux temples'],
            ['SHWEDAGON', 'Pagode dorée birmane'],
            ['BOROBUDUR', 'Temple bouddhiste'],
            ['PRAMBANAN', 'Temple hindou'],
            ['TAJ', 'Début du monument indien'],
            ['MAHAL', 'Palais en Inde'],
            ['AGRA', 'Ville du Taj Mahal'],
            ['FATEHPUR', 'Ville rouge abandonnée'],
            ['SIKRI', 'Citadelle moghole'],
            ['AJANTA', 'Grottes bouddhistes'],
            ['ELLORA', 'Temples rupestres'],
            ['KHAJURAHO', 'Temples érotiques'],
            ['VARANASI', 'Ville sacrée du Gange'],
            ['AMRITSAR', 'Temple d\'or sikh'],
            ['TEMPLE', 'Lieu de culte ancien'],
            ['KINKAKU', 'Pavillon d\'or japonais'],
            ['GINKAKU', 'Pavillon d\'argent'],
            ['TODAI', 'Grand temple de Nara'],
            ['KYOMIZU', 'Temple sur pilotis'],
            ['FUSHIMI', 'Sanctuaire aux torii'],
            ['INARI', 'Milliers de portails'],
            ['NIKKO', 'Sanctuaires japonais'],
            ['ITSUKUSHIMA', 'Torii dans l\'eau'],
            ['MIYAJIMA', 'Île sanctuaire'],
            ['CITE', 'Cité interdite'],
            ['INTERDITE', 'Palais impérial chinois'],
            ['PEKIN', 'Capitale chinoise'],
            ['TEMPLE', 'Temple du Ciel'],
            ['CIEL', 'Sanctuaire céleste'],
            ['PALAIS', 'Palais d\'Été'],
            ['ETE', 'Résidence estivale'],
            ['POTALA', 'Palais du Dalaï-lama'],
            ['LHASSA', 'Capitale du Tibet'],
            ['MURAILLE', 'Long mur de défense'],
            ['CHINE', 'Grande muraille'],

            // Châteaux et palais européens
            ['CHATEAU', 'Demeure fortifiée'],
            ['PALAIS', 'Résidence royale'],
            ['VERSAILLES', 'Château royal français'],
            ['FONTAINEBLEAU', 'Château des rois'],
            ['CHAMBORD', 'Château de la Loire'],
            ['CHENONCEAU', 'Château des Dames'],
            ['AMBOISE', 'Château royal'],
            ['BLOIS', 'Château des États'],
            ['CHAUMONT', 'Château sur Loire'],
            ['AZAY', 'Château miroir'],
            ['RIDEAU', 'Suite d\'Azay'],
            ['VILLANDRY', 'Jardins à la française'],
            ['CHEVERNY', 'Château meublé'],
            ['SAUMUR', 'Château de conte'],
            ['ANGERS', 'Château forteresse'],
            ['VAUX', 'Château baroque'],
            ['VICOMTE', 'Suite de Vaux'],
            ['SCHONBRUNN', 'Palais viennois'],
            ['HOFBURG', 'Palais impérial'],
            ['BELVEDERE', 'Palais baroque'],
            ['NEUSCHWANSTEIN', 'Château de Bavière'],
            ['HOHENSCHWANGAU', 'Château jaune'],
            ['HEIDELBERG', 'Ruines romantiques'],
            ['SANSSOUCI', 'Palais de Potsdam'],
            ['CHARLOTTENBURG', 'Palais berlinois'],
            ['BUCKINGHAM', 'Palais royal Londres'],
            ['WINDSOR', 'Château de la Reine'],
            ['TOWER', 'Tour de Londres'],
            ['EDIMBOURG', 'Château écossais'],
            ['STIRLING', 'Forteresse écossaise'],
            ['ALHAMBRA', 'Palais de Grenade'],
            ['ALCAZAR', 'Forteresse espagnole'],
            ['ESCORIAL', 'Monastère royal'],
            ['PENA', 'Palais coloré'],
            ['SINTRA', 'Ville des palais'],
            ['KREMLIN', 'Forteresse de Moscou'],
            ['PETERHOF', 'Versailles russe'],
            ['CATHERINE', 'Palais baroque'],
            ['ERMITAGE', 'Musée palais'],

            // Sites précolombiens
            ['MACHU', 'Cité inca au Pérou'],
            ['PICCHU', 'Suite de Machu'],
            ['CUZCO', 'Capitale inca'],
            ['SACSAYHUAMAN', 'Forteresse inca'],
            ['OLLANTAYTAMBO', 'Citadelle inca'],
            ['TITICACA', 'Lac sacré'],
            ['TEOTIHUACAN', 'Cité des dieux'],
            ['SOLEIL', 'Pyramide du Soleil'],
            ['LUNE', 'Pyramide de la Lune'],
            ['CHICHEN', 'Site maya'],
            ['ITZA', 'Suite de Chichen'],
            ['KUKULCAN', 'Pyramide maya'],
            ['UXMAL', 'Cité maya'],
            ['PALENQUE', 'Temples mayas'],
            ['TIKAL', 'Pyramides dans jungle'],
            ['COPAN', 'Cité maya Honduras'],
            ['TULUM', 'Cité fortifiée côtière'],
            ['CALAKMUL', 'Pyramides cachées'],
            ['MONTE', 'Site zapotèque'],
            ['ALBAN', 'Suite de Monte'],
            ['MITLA', 'Palais des morts'],

            // Autres monuments célèbres
            ['PETRA', 'Cité dans la roche'],
            ['KHAZNEH', 'Trésor de Petra'],
            ['SELA', 'Rochers taillés'],
            ['STONEHENGE', 'Cercle de pierres'],
            ['AVEBURY', 'Cercle mégalithique'],
            ['CARNAC', 'Alignements bretons'],
            ['NEWGRANGE', 'Tumulus irlandais'],
            ['SANCTUAIRE', 'Lieu sacré'],
            ['MEMORIAL', 'Monument du souvenir'],
            ['MAUSOLEE', 'Tombeau monumental'],
            ['TOMBEAU', 'Sépulture monumentale'],
            ['ZIGGURAT', 'Temple à étages'],
            ['BABEL', 'Tour mythique'],
            ['BABYLONE', 'Cité antique'],
            ['PERSEPOLIS', 'Capitale perse'],
            ['PASARGADES', 'Tombeau de Cyrus'],

            // Monuments modernes
            ['EIFFEL', 'Tour parisienne'],
            ['LIBERTE', 'Statue de New York'],
            ['SYDNEY', 'Opéra australien'],
            ['BURJ', 'Tour de Dubaï'],
            ['KHALIFA', 'Plus haute tour'],
            ['PETRONAS', 'Tours jumelles'],
            ['WILLIS', 'Gratte-ciel de Chicago'],
            ['EMPIRE', 'State Building'],
            ['CHRYSLER', 'Building Art déco'],
            ['REICHSTAG', 'Parlement allemand'],
            ['BUNDESTAG', 'Assemblée fédérale'],
            ['LOUVRE', 'Musée parisien célèbre'],
            ['ORSAY', 'Musée dans gare'],
            ['PRADO', 'Musée madrilène'],
            ['OFFICES', 'Musée florentin'],
            ['BRITANIQUE', 'Musée de Londres'],
            ['METROPOLITAN', 'Met de New York']
        ],
        chateaux: [
            // Châteaux français célèbres
            ['VERSAILLES', 'Château royal de Louis XIV'],
            ['CHAMBORD', 'Chef-d\'œuvre Renaissance'],
            ['CHENONCEAU', 'Château des Dames'],
            ['FONTAINEBLEAU', 'Résidence des rois'],
            ['AMBOISE', 'Château royal de la Loire'],
            ['BLOIS', 'Château des États'],
            ['CHAUMONT', 'Château sur Loire'],
            ['AZAY', 'Reflet dans l\'eau'],
            ['RIDEAU', 'Suite d\'Azay'],
            ['VILLANDRY', 'Jardins magnifiques'],
            ['CHEVERNY', 'Château meublé'],
            ['SAUMUR', 'Château de conte de fées'],
            ['ANGERS', 'Forteresse médiévale'],
            ['CHINON', 'Château de Jeanne d\'Arc'],
            ['LANGEAIS', 'Château fort'],
            ['LOCHES', 'Donjon imposant'],
            ['USSÉ', 'Château de la Belle au bois'],
            ['CHANTILLY', 'Château des princes'],
            ['VAUX', 'Inspirateur de Versailles'],
            ['VICOMTE', 'Suite de Vaux'],
            ['PIERREFONDS', 'Château restauré'],
            ['RAMBOUILLET', 'Résidence présidentielle'],
            ['COMPIEGNE', 'Château impérial'],
            ['MALMAISON', 'Château de Joséphine'],
            ['VINCENNES', 'Donjon parisien'],
            ['COUCY', 'Ruines médiévales'],
            ['GUEDELON', 'Château en construction'],
            ['HAUTEFORT', 'Château périgourdin'],
            ['BEYNAC', 'Château perché'],
            ['CASTELNAUD', 'Château fort'],
            ['BONAGUIL', 'Forteresse imprenable'],
            ['CARCASSONNE', 'Cité médiévale fortifiée'],
            ['FOIX', 'Château ariégeois'],
            ['PEYREPERTUSE', 'Château cathare'],
            ['QUERIBUS', 'Dernier bastion cathare'],
            ['SALSES', 'Forteresse espagnole'],
            ['AIGUESMORTES', 'Tour de Constance'],
            ['TARASCON', 'Château du roi René'],
            ['BEAUCAIRE', 'Château royal'],
            ['NANTES', 'Château des ducs'],
            ['SUSCINIO', 'Château breton'],
            ['FOUGERES', 'Plus grande forteresse'],
            ['VITRE', 'Château breton'],
            ['COMBOURG', 'Château de Chateaubriand'],

            // Châteaux européens
            ['NEUSCHWANSTEIN', 'Château de conte bavarois'],
            ['HOHENSCHWANGAU', 'Château jaune de Bavière'],
            ['HEIDELBERG', 'Ruines romantiques'],
            ['WARTBURG', 'Château de Luther'],
            ['HOHENZOLLERN', 'Nid d\'aigle souabe'],
            ['ELTZ', 'Château médiéval intact'],
            ['LICHTENSTEIN', 'Château perché'],
            ['SANSSOUCI', 'Versailles prussien'],
            ['CHARLOTTENBURG', 'Palais berlinois'],
            ['NYMPHENBURG', 'Palais munichois'],
            ['SCHONBRUNN', 'Versailles autrichien'],
            ['HOFBURG', 'Palais des Habsbourg'],
            ['BELVEDERE', 'Palais baroque viennois'],
            ['EGGENBERG', 'Palais de Graz'],
            ['WINDSOR', 'Plus ancien château habité'],
            ['BUCKINGHAM', 'Palais royal'],
            ['TOWER', 'Tour de Londres'],
            ['EDINBURGH', 'Château écossais'],
            ['STIRLING', 'Forteresse d\'Écosse'],
            ['BALMORAL', 'Résidence royale'],
            ['HIGHCLERE', 'Château de Downton Abbey'],
            ['WARWICK', 'Château médiéval'],
            ['LEEDS', 'Château des reines'],
            ['BODIAM', 'Château fortifié'],
            ['CONWAY', 'Château gallois'],
            ['CAERNARFON', 'Forteresse d\'Édouard'],
            ['HARLECH', 'Château imprenable'],
            ['BEAUMARIS', 'Château parfait'],
            ['DUBLIN', 'Château irlandais'],
            ['BLARNEY', 'Pierre de l\'éloquence'],
            ['PENA', 'Palais romantique'],
            ['SINTRA', 'Château mauresque'],
            ['OBIDOS', 'Village fortifié'],
            ['GUIMARAES', 'Berceau du Portugal'],
            ['ALCAZAR', 'Forteresse de Ségovie'],
            ['SEGOVIA', 'Château espagnol'],
            ['COCA', 'Château mudéjar'],
            ['LOARRE', 'Forteresse romane'],
            ['MANZANARES', 'Château castillan'],
            ['BELMONTE', 'Forteresse Renaissance'],
            ['CREMLIN', 'Forteresse de Moscou'],
            ['PETERHOF', 'Palais des tsars'],
            ['CATHERINE', 'Palais de l\'impératrice'],
            ['PAVLOVSK', 'Résidence impériale'],
            ['TSARSKOIE', 'Village des tsars'],
            ['SELO', 'Suite de Tsarskoie'],
            ['FREDERIKSBORG', 'Château danois'],
            ['KRONBORG', 'Château d\'Hamlet'],
            ['EGESKOV', 'Château sur l\'eau'],
            ['GRIPSHOLM', 'Château suédois'],
            ['DROTTNINGHOLM', 'Palais royal'],
            ['KALMAR', 'Château renaissance'],
            ['VADSTENA', 'Château fortifié'],

            // Architecture et éléments
            ['DONJON', 'Tour centrale et défensive'],
            ['TOUR', 'Construction verticale'],
            ['REMPART', 'Mur d\'enceinte'],
            ['MURAILLE', 'Fortification haute'],
            ['COURTINE', 'Mur entre deux tours'],
            ['MEURTRIERE', 'Ouverture pour tirer'],
            ['CRENEL', 'Ouverture du parapet'],
            ['MERLON', 'Partie pleine du parapet'],
            ['MACHICOULIS', 'Ouverture au sol'],
            ['BRETÈCHE', 'Petit balcon'],
            ['HOURD', 'Galerie en bois'],
            ['BARBACANE', 'Ouvrage avancé'],
            ['POTERNE', 'Porte dérobée'],
            ['HERSES', 'Grille coulissante'],
            ['PORTCULLIS', 'Grille défensive'],
            ['PONT', 'Passage mobile'],
            ['LEVIS', 'Pont basculant'],
            ['DOUVE', 'Fossé rempli d\'eau'],
            ['FOSSE', 'Fossé sec'],
            ['GLACIS', 'Pente douce'],
            ['ESCARPE', 'Mur intérieur du fossé'],
            ['CONTRESCARPE', 'Mur extérieur'],
            ['BASTION', 'Ouvrage pentagonal'],
            ['RAVELIN', 'Ouvrage triangulaire'],
            ['CAPONNIERE', 'Galerie fortifiée'],
            ['CASEMATE', 'Chambre voûtée'],
            ['CHEMIN', 'Passage de ronde'],
            ['RONDE', 'Surveillance des murs'],
            ['PARAPET', 'Muret de protection'],
            ['COURTINE', 'Mur entre tours'],
            ['ENCEINTE', 'Mur d\'enclos'],
            ['BASSE', 'Cour basse'],
            ['COUR', 'Espace central'],
            ['HAUTE', 'Cour haute'],
            ['BASSE', 'Cour extérieure'],
            ['OUBLIETTES', 'Cachot souterrain'],
            ['GEOLE', 'Prison du château'],
            ['CACHOT', 'Cellule étroite'],
            ['SALLE', 'Grande pièce'],
            ['GARDES', 'Pièce des soldats'],
            ['ARMES', 'Salle d\'exposition'],
            ['TRÔNE', 'Salle du roi'],
            ['BANQUET', 'Grande salle à manger'],
            ['CHAPELLE', 'Lieu de culte'],
            ['LOGIS', 'Habitation seigneuriale'],
            ['APPARTEMENTS', 'Pièces privées'],
            ['CHAMBRE', 'Pièce à coucher'],
            ['GARDE', 'Vestibule privé'],
            ['ROBE', 'Vestiaire du roi'],
            ['GALERIE', 'Long couloir décoré'],
            ['ESCALIER', 'Accès aux étages'],
            ['VIS', 'Escalier en colimaçon'],
            ['CHEMINEE', 'Foyer chauffant'],
            ['MANTEAU', 'Décor de cheminée'],
            ['TAPISSERIE', 'Décoration murale'],
            ['TENTURE', 'Tissu mural'],
            ['VITRAIL', 'Fenêtre colorée'],
            ['FENETRE', 'Ouverture vers l\'extérieur'],
            ['LUCARNE', 'Petite fenêtre'],
            ['VOUTE', 'Plafond arqué'],
            ['PLAFOND', 'Partie haute'],
            ['CAISSONS', 'Plafond décoré'],
            ['FRESQUE', 'Peinture murale'],
            ['TOITURE', 'Couverture du château'],
            ['ARDOISE', 'Matériau de toit'],
            ['TUILE', 'Couverture en terre'],
            ['TOURELLE', 'Petite tour'],
            ['ECHAUGUETTE', 'Guérite en encorbellement'],
            ['POIVRIERE', 'Toit conique'],
            ['BEFFROI', 'Tour de guet'],
            ['CLOCHETON', 'Petite tour'],
            ['GIROUETTE', 'Indicateur de vent'],
            ['ORIFLAMME', 'Bannière du seigneur'],
            ['BLASON', 'Armoiries peintes'],

            // Vie de château
            ['SEIGNEUR', 'Maître du château'],
            ['SUZERAIN', 'Seigneur supérieur'],
            ['VASSAL', 'Noble dépendant'],
            ['CHEVALIER', 'Noble guerrier'],
            ['ECUYER', 'Apprenti chevalier'],
            ['PAGE', 'Jeune serviteur noble'],
            ['DAMOISEAU', 'Jeune noble'],
            ['CHATELLAIN', 'Gardien du château'],
            ['CONNÉTABLE', 'Chef des armées'],
            ['SENECHAL', 'Intendant du château'],
            ['PREVOT', 'Administrateur'],
            ['BAILLI', 'Représentant royal'],
            ['MAJORDOME', 'Chef des serviteurs'],
            ['CHAMBELLAN', 'Serviteur personnel'],
            ['INTENDANT', 'Gestionnaire'],
            ['CAPITAINE', 'Chef de la garde'],
            ['SERGENT', 'Officier d\'armes'],
            ['ARCHER', 'Tireur à l\'arc'],
            ['ARBALETRIER', 'Tireur d\'arbalète'],
            ['GUETTEUR', 'Sentinelle'],
            ['PORTIER', 'Gardien de la porte'],
            ['HERAUT', 'Messager officiel'],
            ['MENESTREL', 'Musicien'],
            ['TROUBADOUR', 'Poète chanteur'],
            ['JONGLEUR', 'Amuseur'],
            ['BOUFFON', 'Fou du roi'],
            ['CHAMBRIERE', 'Femme de chambre'],
            ['DAME', 'Noble femme'],
            ['ATOUR', 'Suivante de la dame'],
            ['CHAPELAIN', 'Prêtre du château'],
            ['MOINE', 'Religieux'],
            ['CLERC', 'Lettré religieux'],

            // Événements et cérémonies
            ['TOURNOI', 'Combat chevaleresque'],
            ['JOUTE', 'Combat à cheval'],
            ['ADOUBEMENT', 'Cérémonie de chevalerie'],
            ['BANQUET', 'Grand festin'],
            ['FESTIN', 'Repas somptueux'],
            ['BAL', 'Soirée dansante'],
            ['RECEPTION', 'Accueil solennel'],
            ['AMBASSADE', 'Visite diplomatique'],
            ['CHASSE', 'Poursuite du gibier'],
            ['FAUCONNERIE', 'Chasse au faucon'],
            ['SIEGE', 'Attaque prolongée'],
            ['ASSAUT', 'Attaque violente'],
            ['DEFENSE', 'Protection du château']
        ],
        'jeux-videos': [
            // Héros Nintendo emblématiques
            ['MARIO', 'Plombier moustachu héros de Nintendo'],
            ['LUIGI', 'Frère de Mario en vert'],
            ['PEACH', 'Princesse du Royaume Champignon'],
            ['BOWSER', 'Roi des Koopas tortue'],
            ['YOSHI', 'Dinosaure vert fidèle'],
            ['TOAD', 'Champignon du royaume'],
            ['WARIO', 'Rival cupide de Mario'],
            ['WALUIGI', 'Acolyte de Wario'],
            ['DAISY', 'Princesse de Sarasaland'],
            ['ROSALINA', 'Gardienne des étoiles'],
            ['DONKEY', 'Kong le gorille'],
            ['DIDDY', 'Petit singe agile'],
            ['LINK', 'Héros de la légende de Zelda'],
            ['ZELDA', 'Princesse d\'Hyrule'],
            ['GANONDORF', 'Seigneur des ténèbres'],
            ['SHEIK', 'Identité secrète de Zelda'],
            ['MIDONA', 'Princesse du Crépuscule'],
            ['NAVI', 'Fée qui aide Link'],
            ['EPONA', 'Jument fidèle de Link'],
            ['SAMUS', 'Chasseuse de primes de Metroid'],
            ['RIDLEY', 'Dragon spatial'],
            ['KIRBY', 'Boule rose qui aspire tout'],
            ['DEDEDE', 'Roi autoproclamé'],
            ['METAKNIGHT', 'Chevalier masqué'],
            ['FOX', 'Pilote de Star Fox'],
            ['FALCO', 'Ailier de l\'équipe'],
            ['PIKACHU', 'Souris électrique Pokémon'],
            ['MEWTWO', 'Pokémon légendaire psychique'],
            ['CHARIZARD', 'Dragon de feu volant'],
            ['LUCARIO', 'Pokémon Aura'],
            ['GRENINJA', 'Ninja aquatique'],
            ['JIGGLYPUFF', 'Pokémon chanteur'],
            ['EEVEE', 'Pokémon évolutif'],
            ['SNORLAX', 'Pokémon dormeur'],
            ['MEOWTH', 'Chat qui parle'],
            ['SPLATOON', 'Inklings colorés'],
            ['INKLING', 'Enfant calamar'],
            ['CAPTAIN', 'Falcon pilote'],
            ['FALCON', 'Suite de Captain'],
            ['NESS', 'Enfant télépathe'],
            ['LUCAS', 'Héros de Mother 3'],
            ['OLIMAR', 'Capitaine Pikmin'],
            ['PIKMIN', 'Créatures végétales'],
            ['SHULK', 'Porteur de Monado'],
            ['ISABELLE', 'Assistante canine'],
            ['VILLAGEOIS', 'Habitant d\'Animal Crossing'],
            ['TOM', 'Nook le tanuki'],
            ['NOOK', 'Suite de Tom'],

            // Héros Sega
            ['SONIC', 'Hérisson bleu ultra rapide de Sega'],
            ['TAILS', 'Renard à deux queues'],
            ['KNUCKLES', 'Échidné gardien'],
            ['AMY', 'Hérissonne amoureuse'],
            ['SHADOW', 'Hérisson noir ultime'],
            ['ROUGE', 'Chauve-souris voleuse'],
            ['EGGMAN', 'Docteur Robotnik'],
            ['ROBOTNIK', 'Ennemi de Sonic'],
            ['SILVER', 'Hérisson du futur'],
            ['BLAZE', 'Chatte de feu'],

            // Héros PlayStation
            ['CRASH', 'Bandicoot tournoyant orange'],
            ['COCO', 'Sœur de Crash'],
            ['CORTEX', 'Savant fou'],
            ['SPYRO', 'Petit dragon violet cracheur de feu'],
            ['SPARX', 'Libellule compagnon'],
            ['RATCHET', 'Lombax mécanicien'],
            ['CLANK', 'Robot assistant'],
            ['JAK', 'Héros à l\'éco'],
            ['DAXTER', 'Ottsel bavard'],
            ['SLY', 'Raton voleur'],
            ['COOPER', 'Suite de Sly'],
            ['KRATOS', 'Dieu de la guerre spartiate'],
            ['ATREUS', 'Fils de Kratos'],
            ['NATHAN', 'Chasseur de trésors d\'Uncharted'],
            ['DRAKE', 'Suite de Nathan'],
            ['SULLY', 'Mentor de Drake'],
            ['ELENA', 'Journaliste intrépide'],
            ['ELLIE', 'Survivante de The Last of Us'],
            ['JOEL', 'Protecteur endurci'],
            ['ALOY', 'Chasseuse de Horizon Zero Dawn'],

            // Héros Xbox et Microsoft
            ['CHIEF', 'Spartan Master Chief de Halo'],
            ['MASTER', 'Chef Spartan'],
            ['CORTANA', 'IA de Halo'],
            ['ARBITER', 'Elite honoré'],
            ['MARCUS', 'Soldat de Gears of War'],
            ['FENIX', 'Suite de Marcus'],
            ['BANJO', 'Ours musicien'],
            ['KAZOOIE', 'Oiseau compagnon'],
            ['CONKER', 'Écureuil irrévérent'],

            // Aventuriers et explorateurs
            ['LARA', 'Aventurière de Tomb Raider'],
            ['CROFT', 'Suite de Lara'],
            ['INDIANA', 'Archéologue aventurier'],
            ['JONES', 'Suite d\'Indiana'],

            // Final Fantasy
            ['CLOUD', 'Mercenaire de Final Fantasy VII'],
            ['STRIFE', 'Suite de Cloud'],
            ['TIFA', 'Combattante martiale'],
            ['AERITH', 'Fleuriste de Final Fantasy VII'],
            ['SEPHIROTH', 'Ange déchu'],
            ['VINCENT', 'Pistolier maudit'],
            ['BARRET', 'Leader de l\'Avalanche'],
            ['ZACK', 'Soldat de première'],
            ['SQUALL', 'Mercenaire solitaire'],
            ['TIDUS', 'Joueur de blitzball'],
            ['YUNA', 'Invocatrice courageuse'],
            ['LIGHTNING', 'Guerrière rose'],
            ['NOCTIS', 'Prince de Lucis'],
            ['VIVI', 'Mage noir'],
            ['CHOCOBO', 'Oiseau monture'],
            ['MOOGLE', 'Créature kawaii'],
            ['CACTUAR', 'Cactus rapide'],
            ['BAHAMUT', 'Dragon légendaire'],

            // Sorceleurs et RPG
            ['GERALT', 'Sorceleur chasseur de monstres'],
            ['RIVIA', 'De Rivia'],
            ['CIRI', 'Enfant de la destinée'],
            ['YENNEFER', 'Sorcière puissante'],
            ['TRISS', 'Magicienne rousse'],
            ['ROACH', 'Jument du Sorceleur'],

            // Assassin\'s Creed
            ['EZIO', 'Assassin italien de la Renaissance'],
            ['AUDITORE', 'Famille d\'Ezio'],
            ['ALTAIR', 'Premier assassin'],
            ['CONNOR', 'Assassin amérindien'],
            ['EDWARD', 'Pirate assassin'],
            ['KENWAY', 'Famille de pirates'],
            ['ARNO', 'Assassin français'],
            ['BAYEK', 'Medjay égyptien'],
            ['KASSANDRA', 'Misthios spartiate'],
            ['ALEXIOS', 'Mercenaire grec'],
            ['EIVOR', 'Viking conquérant'],
            ['BASIM', 'Assassin de Bagdad'],

            // Metal Gear
            ['SNAKE', 'Agent infiltré de Metal Gear'],
            ['SOLID', 'Clone de Big Boss'],
            ['NAKED', 'Snake originel'],
            ['OTACON', 'Ingénieur geek'],
            ['OCELOT', 'Tireur d\'élite'],
            ['RAIDEN', 'Cyborg ninja'],

            // Mass Effect
            ['SHEPARD', 'Commandant de Mass Effect'],
            ['GARRUS', 'Turien sniper'],
            ['TALI', 'Quarienne ingénieure'],
            ['LIARA', 'Asari archéologue'],
            ['WREX', 'Krogan mercenaire'],

            // Combattants de jeux de baston
            ['RYU', 'Maître karatéka de Street Fighter'],
            ['KEN', 'Rival de Ryu'],
            ['CHUN', 'Policière chinoise'],
            ['GUILE', 'Militaire américain'],
            ['ZANGIEF', 'Lutteur russe'],
            ['DHALSIM', 'Yogi télékinésiste'],
            ['BLANKA', 'Créature verte'],
            ['VEGA', 'Torero masqué'],
            ['SAGAT', 'Empereur du Muay Thai'],
            ['BISON', 'Dictateur maléfique'],
            ['AKUMA', 'Démon du combat'],
            ['SCORPION', 'Ninja vengeur de Mortal Kombat'],
            ['SUBZERO', 'Maître de glace'],
            ['RAIDEN', 'Dieu du tonnerre'],
            ['LIU', 'Champion shaolin'],
            ['KANG', 'Suite de Liu'],
            ['SONYA', 'Militaire américaine'],
            ['CAGE', 'Johnny acteur'],
            ['JOHNNY', 'Acteur combattant'],
            ['KITANA', 'Princesse édenienne'],
            ['MILEENA', 'Clone maléfique'],
            ['JADE', 'Assassine loyale'],
            ['REPTILE', 'Guerrier saurien'],
            ['ERMAC', 'Fusion d\'âmes'],
            ['SMOKE', 'Ninja cyborg'],
            ['NOOB', 'Saibot ombre'],
            ['SAIBOT', 'Ombre de Noob'],
            ['GORO', 'Prince shokan'],
            ['SHAO', 'Empereur d\'Outremonde'],
            ['KAHN', 'Suite de Shao'],
            ['SHANG', 'Sorcier changeforme'],
            ['TSUNG', 'Suite de Shang'],
            ['KAZUYA', 'Combattant démoniaque de Tekken'],
            ['MISHIMA', 'Famille Mishima'],
            ['HEIHACHI', 'Grand-père Mishima'],
            ['JIN', 'Héritier Mishima'],
            ['PAUL', 'Combattant américain'],
            ['KING', 'Lutteur masqué'],
            ['LAW', 'Imitateur de Bruce Lee'],
            ['NINA', 'Assassine irlandaise'],
            ['YOSHIMITSU', 'Samouraï cyborg'],

            // FPS légendaires
            ['SLAYER', 'Tueur de démons de DOOM'],
            ['DOOMGUY', 'Marine spatial'],
            ['GORDON', 'Scientifique de Half-Life'],
            ['FREEMAN', 'Suite de Gordon'],
            ['ALYX', 'Résistante de Half-Life'],
            ['VANCE', 'Suite d\'Alyx'],
            ['CHELL', 'Cobaye de Portal'],
            ['GLADOS', 'IA maléfique'],
            ['WHEATLEY', 'Sphère idiote'],
            ['TURRET', 'Tourelle mignonne'],

            // Légendes de l\'arcade
            ['PACMAN', 'Légende jaune mangeuse de pac-gommes'],
            ['BLINKY', 'Fantôme rouge'],
            ['PINKY', 'Fantôme rose'],
            ['INKY', 'Fantôme cyan'],
            ['CLYDE', 'Fantôme orange'],
            ['MEGAMAN', 'Robot bleu combattant le Dr Wily'],
            ['PROTOMAN', 'Frère rouge de Megaman'],
            ['RUSH', 'Chien robotique'],
            ['WILY', 'Docteur maléfique'],
            ['BOMBERMAN', 'Poseur de bombes'],
            ['SIMON', 'Belmont chasseur de vampires'],
            ['BELMONT', 'Famille de chasseurs'],
            ['ALUCARD', 'Fils de Dracula'],
            ['DRACULA', 'Vampire légendaire'],
            ['EARTHWORM', 'Ver de terre héroïque'],
            ['JIM', 'Dans une armure'],
            ['RAYMAN', 'Héros sans bras ni jambes'],

            // RPG et aventure
            ['SORA', 'Porteur de Keyblade de Kingdom Hearts'],
            ['RIKU', 'Ami rival de Sora'],
            ['KAIRI', 'Amie de Sora'],
            ['ROXAS', 'Simili de Sora'],
            ['AXEL', 'Organisation XIII'],
            ['ANSEM', 'Chercheur des ténèbres'],
            ['XEHANORT', 'Maître du mal'],
            ['ARTHUR', 'Hors-la-loi de Red Dead Redemption'],
            ['MORGAN', 'Suite d\'Arthur'],
            ['JOHN', 'Marston cowboy'],
            ['MARSTON', 'Suite de John'],
            ['DUTCH', 'Chef de bande'],
            ['SADIE', 'Hors-la-loi vengeresse'],
            ['GERALT', 'De Riv'],
            ['DRAGONBORN', 'Dovahkiin dragon'],
            ['DOVAHKIIN', 'Né-dragon'],
            ['ALDUIN', 'Dragon dévoreur'],
            ['PAARTHURNAX', 'Dragon sage'],
            ['LYDIA', 'Huscarl fidèle'],

            // Jeux indépendants
            ['SANS', 'Squelette blagueur'],
            ['PAPYRUS', 'Squelette énergique'],
            ['UNDYNE', 'Guerrière poisson'],
            ['TORIEL', 'Mère protectrice'],
            ['ASGORE', 'Roi des monstres'],
            ['FLOWEY', 'Fleur maléfique'],
            ['FRISK', 'Enfant déterminé'],
            ['STEVE', 'Héros carré de Minecraft'],
            ['ALEX', 'Héroïne de Minecraft'],
            ['CREEPER', 'Monstre explosif vert'],
            ['ENDERMAN', 'Créature téléportante'],
            ['SHOVEL', 'Chevalier à la pelle'],
            ['KNIGHT', 'Chevalier héroïque'],
            ['HOLLOW', 'Chevalier creux'],
            ['HORNET', 'Princesse guerrière'],
            ['ZAGREUS', 'Prince des enfers'],
            ['HADES', 'Dieu des morts'],
            ['THANATOS', 'Incarnation de la mort'],

            // Termes génériques
            ['BOSS', 'Ennemi puissant final'],
            ['MINIBOSS', 'Ennemi intermédiaire'],
            ['MONSTRE', 'Créature hostile'],
            ['ENNEMI', 'Adversaire à combattre'],
            ['NIVEAU', 'Étape du jeu'],
            ['MONDE', 'Zone d\'aventure'],
            ['QUETE', 'Mission à accomplir'],
            ['MISSION', 'Objectif à remplir'],
            ['COFFRE', 'Contient des trésors'],
            ['TRESOR', 'Objet précieux'],
            ['OBJET', 'Item à collecter'],
            ['ARME', 'Pour combattre'],
            ['EPEE', 'Lame tranchante'],
            ['BOUCLIER', 'Protection défensive'],
            ['ARMURE', 'Équipement protecteur'],
            ['POTION', 'Boisson de soin'],
            ['MAGIE', 'Pouvoir surnaturel'],
            ['SORT', 'Formule magique'],
            ['POUVOIR', 'Capacité spéciale'],
            ['VIE', 'Points de santé'],
            ['MANA', 'Énergie magique'],
            ['ENERGIE', 'Ressource vitale'],
            ['EXPERIENCE', 'Points à gagner'],
            ['SCORE', 'Points de jeu'],
            ['HIGHSCORE', 'Meilleur score'],
            ['RECORD', 'Performance maximale'],
            ['VICTOIRE', 'Gagner la partie'],
            ['DEFAITE', 'Perdre la partie'],
            ['CONTINUE', 'Reprendre le jeu'],
            ['GAMEOVER', 'Fin de partie'],
            ['CHECKPOINT', 'Point de sauvegarde'],
            ['SAUVEGARDE', 'Enregistrer la progression'],
            ['CHARGEMENT', 'Restaurer la partie'],
            ['MANETTE', 'Contrôleur de jeu'],
            ['JOYSTICK', 'Manche à balai'],
            ['BOUTON', 'Commande à presser'],
            ['START', 'Commencer'],
            ['SELECT', 'Sélectionner'],
            ['PAUSE', 'Mettre en pause'],
            ['OPTIONS', 'Réglages du jeu'],
            ['MENU', 'Interface de navigation'],
            ['GRAPHISMES', 'Visuels du jeu'],
            ['PIXEL', 'Point d\'image'],
            ['SPRITE', 'Image 2D'],
            ['TEXTURE', 'Surface visuelle'],
            ['FPS', 'Images par seconde'],
            ['LAG', 'Retard de connexion'],
            ['BUG', 'Erreur de programmation'],
            ['GLITCH', 'Anomalie du jeu'],
            ['CHEAT', 'Code de triche'],
            ['EASTER', 'Œuf de Pâques'],
            ['EGG', 'Secret caché'],
            ['BONUS', 'Récompense supplémentaire'],
            ['SPEEDRUN', 'Course contre la montre'],
            ['MULTIJOUE', 'Mode à plusieurs'],
            ['COOP', 'Coopération'],
            ['VERSUS', 'Combat contre'],
            ['ONLINE', 'En ligne'],
            ['OFFLINE', 'Hors ligne'],
            ['SKIN', 'Apparence personnalisée'],
            ['MOD', 'Modification du jeu'],
            ['PATCH', 'Mise à jour correctrice'],
            ['DLC', 'Contenu téléchargeable'],
            ['EXPANSION', 'Extension du jeu'],
            ['REMASTER', 'Version améliorée'],
            ['REMAKE', 'Refonte complète'],
            ['SEQUEL', 'Suite d\'un jeu'],
            ['PREQUEL', 'Préquelle d\'un jeu'],
            ['TRILOGY', 'Trilogie de jeux'],
            ['SAGA', 'Série de jeux'],
            ['FRANCHISE', 'Série commerciale'],
            ['CONSOLE', 'Plateforme de jeu'],
            ['NINTENDO', 'Fabricant japonais'],
            ['SONY', 'Créateur PlayStation'],
            ['MICROSOFT', 'Créateur Xbox'],
            ['SEGA', 'Ancien rival Nintendo'],
            ['ARCADE', 'Salle de jeux'],
            ['RETRO', 'Jeux anciens'],
            ['PIXEL', 'Art pixelisé'],
            ['INDIE', 'Jeu indépendant']
        ]
    };

    let wordCount = 0;
    let definitionsAdded = 0;
    const now = new Date().toISOString();

    // Récupérer tous les mots existants en une seule requête
    const { all } = require('../../server/turso-db');
    const existingWords = await all('SELECT id, word, definition, theme_slug FROM word_search_words');
    const existingMap = new Map();
    existingWords.forEach(w => {
        const key = `${w.theme_slug || 'NULL'}:${w.word}`;
        existingMap.set(key, w);
    });

    // Préparer les inserts et updates
    const toInsert = [];
    const toUpdate = [];

    // Traiter les mots génériques
    for (const [word, definition] of genericWords) {
        const key = `NULL:${word}`;
        const existing = existingMap.get(key);

        if (!existing) {
            toInsert.push([null, word, definition, now]);
        } else if (definition && existing.definition !== definition) {
            toUpdate.push([definition, existing.id]);
        }
    }

    // Traiter les mots par thème
    for (const [themeSlug, words] of Object.entries(wordLists)) {
        for (const [word, definition] of words) {
            const key = `${themeSlug}:${word}`;
            const existing = existingMap.get(key);

            if (!existing) {
                toInsert.push([themeSlug, word, definition, now]);
            } else if (definition && existing.definition !== definition) {
                toUpdate.push([definition, existing.id]);
            }
        }
    }

    // Exécuter les inserts par batch
    if (toInsert.length > 0) {
        for (const [themeSlug, word, definition, createdAt] of toInsert) {
            await run(
                'INSERT INTO word_search_words (theme_slug, word, definition, created_at) VALUES (?, ?, ?, ?)',
                [themeSlug, word, definition, createdAt]
            );
        }
        wordCount = toInsert.length;
    }

    // Exécuter les updates par batch
    if (toUpdate.length > 0) {
        for (const [definition, id] of toUpdate) {
            await run(
                'UPDATE word_search_words SET definition = ? WHERE id = ?',
                [definition, id]
            );
        }
        definitionsAdded = toUpdate.length;
    }

    console.log(`  ✅ ${wordCount} new words seeded, ${definitionsAdded} definitions added (${genericWords.length} generic + ${Object.keys(wordLists).length} themes)`);
}

module.exports = { seedWords };
